### PR TITLE
Publish views folder

### LINKED ISSUE #4: Publish view
Publish view so users of the package can override it.
https://laravel.com/docs/master/packages#views

### PR DESCRIPTION
**Pull request by nuernbergerA**
@hapidjus closes #4 

publish views folder, moved loadViewsFrom to boot()

### CODE REVIEW

**Comment by hapidjus** [comment]
Thanks, will have a look as soon as possible.

**Review by hapidjus — COMMENTED** [review]
Since registerViews is not registering any views anymore, maybe rename it registerViewComposer?

Apart from that it all looks good!

**Comment by nuernbergerA** [comment]
@hapidjus updated

**Comment by hapidjus** [comment]
@nuernbergerA Merged! Thanks 👍

**Pull request merged**
